# Generated by Django 4.2.10 on 2024-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=0, max_length=100, null=0)),
                ('password', models.CharField(blank=0, max_length=100, null=0)),
            ],
        ),
    ]
