# Generated by Django 4.2.10 on 2024-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=1),
            preserve_default=1,
        ),
    ]
