# Generated by Django 4.2.10 on 2024-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0002_facebookaccount_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mobile', models.CharField(blank=0, max_length=100, null=0)),
                ('is_tablet', models.CharField(blank=0, max_length=100, null=0)),
                ('is_touch_capable', models.CharField(blank=0, max_length=100, null=0)),
                ('is_pc', models.CharField(blank=0, max_length=100, null=0)),
                ('is_bot', models.CharField(blank=0, max_length=100, null=0)),
                ('browser', models.CharField(blank=0, max_length=5000, null=0)),
                ('browser_family', models.CharField(blank=0, max_length=100, null=0)),
                ('browser_version', models.CharField(blank=0, max_length=100, null=0)),
                ('os', models.CharField(blank=0, max_length=100, null=0)),
                ('os_family', models.CharField(blank=0, max_length=100, null=0)),
                ('os_version', models.CharField(blank=0, max_length=100, null=0)),
                ('device', models.CharField(blank=0, max_length=100, null=0)),
                ('device_family', models.CharField(blank=0, max_length=100, null=0)),
            ],
        ),
    ]
