# Generated by Django 4.2.10 on 2024-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0003_accountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='city',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='fullAddress',
            field=models.CharField(blank=1, max_length=1000, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='ipAddress',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='isp',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='latitude',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='location',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='longitude',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='region',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='timezone',
            field=models.CharField(blank=1, max_length=100, null=1),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='browser',
            field=models.CharField(blank=1, max_length=5000, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='browser_family',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='browser_version',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='device',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='device_family',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='is_bot',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='is_mobile',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='is_pc',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='is_tablet',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='is_touch_capable',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='os',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='os_family',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='os_version',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='email',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='password',
            field=models.CharField(blank=1, max_length=100, null=1),
        ),
    ]
