# Generated by Django 4.2.10 on 2024-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0004_accountinfo_city_accountinfo_fulladdress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=1),
            preserve_default=1,
        ),
    ]
